spring.datasource.url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.xrfsffrtkishfhhhblse
spring.datasource.password=Gym123456!!RQA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache: true
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.main.allow-circular-references= true

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript
server.compression.min-response-size=1024